name: RASEL

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.2
  # Responsive
  flutter_screenutil: ^5.7.0
  # Bloc
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  # video
  video_player: ^2.3.0

  cached_network_image:
  # app route
  go_router:
  # l & r
  dartz:
  equatable: ^2.0.5
  shared_preferences: ^2.0.17
  intl: ^0.17.0
  google_fonts: ^4.0.1
  share_plus: ^6.3.4
  url_launcher: ^6.1.6
  animated_splash_screen: ^1.3.0
  flutter_spinkit: ^5.1.0
  hexcolor: ^3.0.1
  image_picker: ^0.8.6+1
  font_awesome_flutter:
  percent_indicator:
  flutter_launcher_icons: ^0.13.1
  # Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.11
  google_sign_in:
  flutter_login_facebook:
  firebase_database:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-no-background.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
